### ISSUE TITLE
Pointer stays in the top left corner of the page.

### ISSUE THREAD

**Issue by ramaseshan** [ahomu/Talkie#3]
![31-05-2015--21 28_scrot](https://cloud.githubusercontent.com/assets/5002019/7902602/367e5d50-07dc-11e5-86bd-4a9b6a8185e2.png)

In pointer mode, the pointer stays on the top left corner of the page and dosent move.

Browser : Firefox
Version : 38
OS - Fedora 21

**Comment by ahomu** [comment]
Thanks for the report! This problem was fixed in 0.8.1. :)
