### ISSUE TITLE
The `dist/talkie.js` and `dist/talkie.min.js` files are empty

### ISSUE THREAD

**Issue by domhnallmurphy-examtime** [ahomu/Talkie#4]
I was attempting to run the basic example from the README, but it won't run as the `/dist` files are empty.  

I am guessing I can generate these from the source by running the appropriate task, but it would be a lot easier if the current versions were pre-generated.

**Comment by ahomu** [comment]
sorry, it was a mistake.  Now the latest dist is not empty. thanks!

**Comment by domhnallmurphy-examtime** [comment]
Great thanks.
