### ISSUE TITLE
マークダウン記法で<br>が効きません

### ISSUE THREAD

**Issue by steelydylan** [ahomu/Talkie#6]
お世話になっております。

Talkie.jsを使わせて頂いているのですが、前のバージョンでは<br>で改行がされたはずなのですが、現在使用中のv.0.8.1で<br>を使って改行がされず、そのまま<br>が残ってしまいました。
行末にスペースを二つ以上いれても改行がされません。

これは、マークダウン記法が変わったのでしょうか？

ご教示お願いします。

**Comment by ahomu** [comment]
ご報告ありがとうございます。

>現在使用中のv.0.8.1でを使って改行がされず、そのままが残ってしまいました。

markdown パーサを `markdown-it` に変更した際の設定漏れによるバグでした。
v0.8.2 で修正しています。:)

>行末にスペースを二つ以上いれても改行がされません。

これは手元のChrome 42 で見た限り v0.8.1 で確認しても有効でした。

**Comment by steelydylan** [comment]
ありがとうございます。

では、早速最新版のTalkie.jsを使わせていただきます。
